### ISSUE TITLE
Maybe show the signal that got to crash

### ISSUE THREAD

**Issue by X-Ryl669** [TylerGlaiel/Crashlogs#2]
If you ever intend to support a POSIX version, it would be a good idea to capture the signal number that leads to the crash and save it too, since it's a valuable information.

Please notice however that, on POSIX system, it's not possible to call many functions from a signal handler (since the kernel stacked up the signal handler call on a possibly corrupt stack and/or from a system call that crashed). It seems, at first glance, that you're using file I/O, memory allocation and many other functions that are forbidden to be used.

**Comment by TylerGlaiel** [comment]
https://github.com/TylerGlaiel/Crashlogs/pull/6
