### ISSUE TITLE
Interest in Adding a Build System?

### ISSUE THREAD

**Issue by ptsouchlos** [TylerGlaiel/Crashlogs#3]
Is there any desire to add a build system to this project (i.e. CMake) and/or unit tests? Just trying to gauge where this project will go in the future.

**Comment by TylerGlaiel** [comment]
this is a 200 line file you include in your project and call 1 function to use. it doesn't need a build system

**Comment by TylerGlaiel** [comment]
if someone wants to add tests and samples into a separate folder I'll add them, but only if they do not include any dependencies
